// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ModalClose() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return nil
	})
}

func AddPositionModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"positionModal\" class=\"modal\"><div class=\"modal-content\"><div class=\"modal-header\"><h3>Add Position</h3><button class=\"close-btn\" hx-get=\"/modal/close\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\">&times;</button></div><form id=\"positionForm\" class=\"modal-form\" hx-post=\"/api/positions/add\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\"><div class=\"form-group\"><label>Position Type</label> <select id=\"positionType\" name=\"positionType\" required hx-get=\"/modal/add-position-fields.html\" hx-target=\"#conditional-fields\" hx-swap=\"innerHTML\" hx-trigger=\"load, change\"><option value=\"stock\">Stock</option> <option value=\"option\">Option</option></select></div><div class=\"form-group\"><label>Ticker</label> <input type=\"text\" id=\"ticker\" name=\"ticker\" required placeholder=\"e.g., AAPL\" style=\"text-transform: uppercase\" oninput=\"this.value = this.value.toUpperCase()\"></div><div id=\"conditional-fields\"></div><div class=\"form-group\"><label>Open Date</label> <input type=\"date\" id=\"openDate\" name=\"openDate\"></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn btn-primary\">Add Position</button> <button type=\"button\" class=\"btn btn-secondary\" hx-get=\"/modal/close\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\">Cancel</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AddPositionStockFields() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"form-group\"><label>Quantity</label> <input type=\"number\" id=\"quantity\" name=\"quantity\" required step=\"0.01\" placeholder=\"100\"></div><div class=\"form-group\"><label>Cost Basis / Price</label> <input type=\"number\" id=\"costBasis\" name=\"costBasis\" required step=\"0.01\" placeholder=\"150.00\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AddPositionOptionFields() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"form-group\"><label>Option Type</label> <select id=\"optionType\" name=\"optionType\" required><option value=\"Call\">Call</option> <option value=\"Put\">Put</option> <option value=\"CSP\">Cash Secured Put (CSP)</option> <option value=\"CC\">Covered Call (CC)</option></select></div><div class=\"form-group\"><label>Strike Price</label> <input type=\"number\" id=\"strike\" name=\"strike\" step=\"0.01\" placeholder=\"155.00\" required></div><div class=\"form-group\"><label>Premium (per contract)</label> <input type=\"number\" id=\"premium\" name=\"premium\" step=\"0.01\" placeholder=\"5.00\" required></div><div class=\"form-group\"><label>Number of Contracts</label> <input type=\"number\" id=\"quantity\" name=\"quantity\" step=\"1\" placeholder=\"1\" value=\"1\" required></div><div class=\"form-group\"><label>Expiration Date</label> <input type=\"date\" id=\"expDate\" name=\"expDate\" required></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ImportCSVModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"modal\"><div class=\"modal-content\"><div class=\"modal-header\"><h3>Import Trades from CSV</h3><button class=\"close-btn\" hx-get=\"/modal/close\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\">&times;</button></div><form hx-post=\"/api/import-csv\" hx-encoding=\"multipart/form-data\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\"><div class=\"form-group\"><label>CSV File</label> <input type=\"file\" name=\"csvFile\" accept=\".csv\" required><p style=\"font-size: 0.875rem; color: var(--text-secondary); margin-top: 0.5rem;\">Upload your brokerage CSV file with trade history</p></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn btn-primary\">Import</button> <button type=\"button\" class=\"btn btn-secondary\" hx-get=\"/modal/close\" hx-target=\"#modal-container\" hx-swap=\"innerHTML\">Cancel</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
